# Generated by Django 3.2.4 on 2021-07-13 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('Action', 'ACTION'), ('Adventure', 'Adventure'), ('Comedy', 'COMEDY'), ('Documentary', 'DOCUMENTARY'), ('Drama', 'DRAMA'), ('Horror', 'HORROR'), ('Sci-Fi', 'SCI_FI'), ('Thriller', 'THRILLER'), ('Fantasy', 'FANTASY'), ('Fiction', 'FICTION'), ('Other', 'OTHER')], default='Other', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(default='movielist_slug', unique=True)),
                ('storyline', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('avg_rating', models.FloatField(default=0)),
                ('number_rating', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('genre_type', models.ManyToManyField(related_name='genre_type_field', to='watchlist_app.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='StreamPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(default='streamplatform_slug', unique=True)),
                ('about', models.CharField(max_length=150)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='review_slug', unique=True)),
                ('rating', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('review_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_field', to='watchlist_app.movielist')),
            ],
        ),
        migrations.AddField(
            model_name='movielist',
            name='streaming_platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_platform_field', to='watchlist_app.streamplatform'),
        ),
    ]
