# Generated by Django 3.2.4 on 2021-08-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0002_alter_review_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
