# Generated by Django 3.2.4 on 2021-08-24 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_alter_streamplatform_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='streaming_platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_platform', to='watchlist_app.streamplatform'),
        ),
    ]
