# Generated by Django 3.2.4 on 2021-08-24 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_alter_movielist_streaming_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielist',
            name='streaming_platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_platform_field', to='watchlist_app.streamplatform'),
        ),
    ]
